[package]
name = "raiblocks-load-tester"
version = "0.1.0"

[dependencies]
clap = "2.29.2"
error-chain = "0.11.0"
serde_json = "1.0.9"
serde = "1.0.27"
hyper = "0.11.15"
tokio-core = "0.1.12"
futures = "0.1.17"
rand = "0.4.2"
serde_derive = "1.0.27"
tokio-process = "0.1.5"
time = "0.1.39"
