language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: ONE_TIME_TESTS=true
      services:
        - docker
      addons:
        apt:
          packages:
            - doxygen
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TSAN=1
      services:
        - docker
    - os: linux
      dist: trusty
      sudo: required
      env:
        - ASAN=1
      services:
        - docker
    - os: osx

compiler:
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo mkdir -p /etc/docker && echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json && sudo service docker restart; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install qt5 && brew cask install xquartz && brew upgrade boost && brew install rust; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 40 ci/build-docker-image.sh docker/ci/Dockerfile nanocurrency/nano-ci; fi

script:
  - if [ -n "$ONE_TIME_TESTS" ]; then ci/check-commit-format.sh; fi
  - if [ -n "$ONE_TIME_TESTS" ]; then doxygen doxygen.config; fi # TODO also deploy the built HTML
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ci/build-travis.sh "/usr/local/opt/qt5/lib/cmake/Qt5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run -v $TRAVIS_BUILD_DIR:/workspace nanocurrency/nano-ci /bin/bash -c "cd /workspace && ASAN=${ASAN} TSAN=${TSAN} ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}"; fi

deploy:
  skip_cleanup: true
  provider: script
  script: travis_wait 80 ci/deploy-docker.sh
  on:
    condition: -n "$ONE_TIME_TESTS"
